services:
  postgres:
    image: 'postgres:latest'
    #todo .env file
    environment:
      - 'POSTGRES_DB=exception-analyzer-db'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432'
