spring:

  application:
    name: exception-analyzer

  threads:
    virtual:
      enabled: true

  jpa:
    hibernate:
      #todo Liquibase and set validate
      ddl-auto: update

  datasource:
    #todo hide it. Now its dev
    url: jdbc:postgresql://localhost:5432/exception-analyzer-db
    username: admin
    password: admin

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: exception-events
      key-deserializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
